version: "3"
services:

  redis:
    image: redis
    hostname: redis
    ports:
        - 6379:6379

#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis