server:
  port: 8080

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  redis:
    port: 6379
    host: 127.0.0.1
  thymeleaf:
    prefix: file:src/main/resources/templates/
    check-template-location: true
    cache: false
